name = input("Please Enter your name: ")
print(f"Hello {name}")
print(f"Welcome to the MADLIBS Game")
print("Input each options acordingly, to write your story")

adjective = input("Enter an Adjective: ")
adjective1 = input("Enter an Adjective: ")
typeOfbird = input("Enter a type of bird: ")
verb = input("Enter a Verb(past tense): ")
verb1 = input("Enter a verb: ")
relativeName = input("Enter a relative's name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verb1 = input("Enter a verb ending with -ing: ")
bodyPart = input("Enter part of the body (plural): ")
noun1 = input("Enter a noun (plural): ")
verb2 = input("Enter a verb ending with -ing: ")
noun2 = input("Enter a noun: ")

print(f"It was a {adjective}, cold November day.")
print(f"I woke up to the {adjective1} smell of {typeOfbird} roasting in the room in a house downstairs.")
print(f"I {verb} down the stairs to see if I could help {verb1} the dinner.")
print(f"My mon said, see if {relativeName} needs a fresh {noun}.")
print(f"So I carried a tray of glasses full of a {liquid} into the {verb1} room.")
print(f"When I got there, I couldn't believe my {bodyPart}!")
print(f"There were {noun1} {verb2} on the {noun}!")

print("If you enjoyed this game, please leave a star/like")
print("If you have any contributions, suggestions, questions, please leave it in the comment box. \nThank you\n")
